run_name: 'crossdocked_ca_cond_07072023_egnn'
logdir: '/data/Repositories/Lab_Repositories/GCDM-SBDD/logs/train'
wandb_params:
  mode: 'online'  # disabled, offline, online
  entity: 'bml-lab'
dataset: 'crossdock'
datadir: '/data/Repositories/Lab_Repositories/GCDM-SBDD/data/processed_crossdock_noH_ca_only_temp'
enable_progress_bar: False
num_sanity_val_steps: 0

mode: 'pocket_conditioning'
pocket_representation: 'CA'
batch_size: 16
accumulate_grad_batches: 2
lr: 1.0e-4
n_epochs: 1000
num_workers: 1
gpus: 1
clip_grad: True
augment_rotation: False
augment_noise: 0
strategy: ddp_find_unused_parameters_true

auxiliary_loss: False
loss_params:
  max_weight: 1.0
  schedule: 'linear'
  clamp_lj: 3.0

net_dynamics_params:
  model_name: egnn
  device: 'cuda'
  edge_cutoff: null
  joint_nf: 32
  hidden_nf: 256
  n_layers: 6
  attention: True
  tanh: True
  norm_constant: 1
  inv_sublayers: 1
  sin_embedding: False
  aggregation_method: 'sum'
  normalization_factor: 100  # used if aggregation_method='sum'

diffusion_params:
  diffusion_steps: 1000
  diffusion_noise_schedule: 'polynomial_2'
  diffusion_noise_precision: 1.0e-5
  diffusion_loss_type: 'l2'
  normalize_factors: [1, 4]  # [x, h]

eval_epochs: 25
visualize_sample_epoch: 25
visualize_chain_epoch: 25
eval_params:
  n_eval_samples: 100
  eval_batch_size: 100
  smiles_file: '/data/Repositories/Lab_Repositories/GCDM-SBDD/data/processed_crossdock_noH_ca_only_temp/train_smiles.npy'
  n_visualize_samples: 5
  keep_frames: 100