run_name: 'my_first_run'
logdir: '/path/to/logdir/'
wandb_params:
  mode: 'online'  # disabled, offline, online
  entity: 'my_wandb_entity'
dataset: 'bindingmoad'
datadir: '/path/to/processed_bindingmoad/'
enable_progress_bar: False
num_sanity_val_steps: 0

mode: 'joint'  # joint, pocket_conditioning, pocket_conditioning_simple
pocket_representation: 'CA'  # CA, full-atom
batch_size: 32
accumulate_grad_batches: 1
lr: 1.0e-4
n_epochs: 1000
num_workers: 0
gpus: 1
clip_grad: True
augment_rotation: False
augment_noise: 0

auxiliary_loss: False
loss_params:
  max_weight: 1.0
  schedule: 'linear'
  clamp_lj: 3.0

net_dynamics_params:
  model_name: gcpnet
  device: 'cuda'
  edge_cutoff: null
  joint_nf: 16
  hidden_nf: 256
  n_layers: 5
  attention: True
  tanh: True
  norm_constant: 1
  inv_sublayers: 1
  sin_embedding: False
  aggregation_method: 'sum'
  normalization_factor: 100  # used if aggregation_method='sum'

diffusion_params:
  diffusion_steps: 1000
  diffusion_noise_schedule: 'polynomial_2'  # learned, cosine
  diffusion_noise_precision: 1.0e-5
  diffusion_loss_type: 'l2'  # vlb, l2
  normalize_factors: [1, 4]  # [x, h]

eval_epochs: 50
visualize_sample_epoch: 20
visualize_chain_epoch: 20
eval_params:
  n_eval_samples: 100
  eval_batch_size: 100
  smiles_file: '/path/to/train_smiles.npy'
  n_visualize_samples: 5
  keep_frames: 100