defaults:
  - gcpnet/model_cfg: gcp_model.yaml
  - gcpnet/module_cfg: gcp_module.yaml
  - gcpnet/layer_cfg: gcp_interaction_layer.yaml
  - _self_

config: ???
resume: null
overwrite_config_with_checkpoint: True
log_every_n_steps: 50